### PR TITLE
Use https to git clone

### PR DESCRIPTION
**Pull request by alfonso-salces**

### CODE REVIEW

**Comment by stronk7** [comment]
Hi @alfonso-salces ,

many thanks for your PR. Note that exactly the same issue has been fixed by #210 . I just saw that one first, no matter your one arrived first, sorry for that.

So I'm closing this now. Again, thanks.

Ciao :-)

**Comment by stronk7** [comment]
From @scara:

> for the sake of community refs 😉, it was fixed by #211.

(sorry for the mixing of issues, 208, 209, 210, 211...)

**Comment by scara** [comment]
No need to apologize @stronk7!
I was joking 🤡 .

Keep up the good work,
Matteo

**Comment by stronk7** [comment]
Heh, NP!

**Pull request closed without merging**
