### PR TITLE
Add support for local.yml

### PR DESCRIPTION
**Pull request by andrewnicols**
This change adds support for a local yml file to include any customisations that users may wish to include as standard.

This may, for example include changes to existing containers, or it may include the addition of additional containers such as database admin tooling, or proxy servers.

### CODE REVIEW

**Comment by scara** [comment]
Hi @andrewnicols,
LGTM!

Is there any reason not to kept aligned even [`moodle-docker-compose.cmd`](https://github.com/moodlehq/moodle-docker/blob/master/bin/moodle-docker-compose.cmd)?

TIA,
Matteo

**Comment by andrewnicols** [comment]
Only because I totally forgot when I wrote this several months ago (and am still amazed that people use Windows for development).

I don't have a Windows machine to be able to test it I'm afraid.

**Comment by stronk7** [comment]
Ah, and would be great if we can add the very same `ECHO "Including local options from...` to the Windows one. Sorry just saw it now.

**Comment by andrewnicols** [comment]
> Only tiny suggestion that I'd do here is to add a comment about ensuring that the loading of the local.yml always remains the last one before calling compose. Just to avoid forgetting about that in the future.

Done :)

> Ah, and would be great if we can add the very same ECHO "Including local options from... to the Windows one. Sorry just saw it now.

And done - hope I got this right.

**Comment by stronk7** [comment]
Thanks, looks perfect! Will test shortly...

**Comment by stronk7** [comment]
Tested both under Unix and Windows, it worked great, so far!

**Pull request merged**
