### PR TITLE
Split browser name before in case it uses tags

### PR DESCRIPTION
**Pull request by crazyserver**

### CODE REVIEW

**Comment by stronk7** [comment]
Hi @crazyserver ,

change looks ok, good stuff!

Only question I've here is if, maybe, we also have to move the "split" code in `bin/moodle-docker-compose.cmd`. While the code managing the app for Windows is different from the Unix one... surely there we should be also looking for the `MOODLE_DOCKER_BROWSER_NAME`, and not for the whole `MOODLE_DOCKER_BROWSER` that can come with tags.

I think that, with that little detail covered... this will be perfect to be landed.

Ciao :-)

**Comment by crazyserver** [comment]
Thanks Eloy! Can you review again? :-)

**Comment by stronk7** [comment]
I've relaunched 2-3 jobs that failed (hopefully random ones). Code-wise, it seems that now everything is already in place, with the split happening before the browser name is used, so all ok.

**Comment by stronk7** [comment]
Sold, thanks!

**Pull request merged**
