### PR TITLE
Podman support for podman-compose > 1.0.0

### PR DESCRIPTION
**Pull request by dahrens**
This commit reverts previous commits:

- 0f5c0b9a6c861568b5a04afc9131d0262b1c5b34
- 58837a02a407bb4b9092896baa0351482ce7c00c

Those are no longer necessary since podman-compose 1.0
was released. Additionally this commit adds some basic
information about using podman to run this repository
to the README.

This is related to #200 and #172.

### CODE REVIEW

**Comment by dahrens** [comment]
Looks like unencrypted clones using the git protocol used in [app_setup.sh](https://github.com/moodlehq/moodle-docker/blob/master/tests/app-setup.sh) are [no longer supported by github](https://github.blog/2021-09-01-improving-git-protocol-security-github/).

**Comment by stronk7** [comment]
Hi @dahrens and @scara ,

unfortunately I cannot give to this a try now... so if I get a thumbs up from both you about this issue I'm more than happy trusting you and merging it.

Ciao :-)

**Comment by dahrens** [comment]
I totally understand that @stronk7
I guess it is up to @scara to provide more feedback than an emoji :) Otherwise I will just close this PR.

**Comment by scara** [comment]
Hi @dahrens,
> I guess it is up to @scara to provide more feedback than an emoji :)

🤣 

I'm playing with both `docker` and `podman` in my dev env but for _Moodle Docker Toolbox_.
Will give your PR a try in the weekend, spare time permitted.

HTH,
Matteo

**Comment by dahrens** [comment]
Hey @scara - maybe you find some time to write down your concerns?

**Comment by dahrens** [comment]
I doubt this will be merged, therefore closing the PR. :wave:

**Pull request closed without merging**
