### PR TITLE
add suport for .env files

### PR DESCRIPTION
**Pull request by jpahullo**
This is also really helpful since you do not need to `export` variables and have side effects when running several instances.

### CODE REVIEW

**Comment by jpahullo** [comment]
The same issue on `geoip` applies to this PR, as mentioned by @scara.

**Comment by jpahullo** [comment]
Hi!
Should I update this branch too to the latest master branch?

**Comment by jpahullo** [comment]
Could this PR be approved and accepted into the repository?

Thanks!

**Comment by systemovich** [comment]
> Hi!
> Should I update this branch too to the latest master branch?

I think you should. Hopefully that will resolve the conflicts and pass all checks.

**Comment by jpahullo** [comment]
by now, there is an error on the CI but is nothing related to the code related to this PR: 319.2:

```
There was 1 failure:
1) core_block_externallib_testcase::test_get_dashboard_blocks_default_dashboard
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'displaycategories'
+'version'
/var/www/html/blocks/tests/externallib_test.php:270
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit --verbose "core_block_externallib_testcase" blocks/tests/externallib_test.php
--
```

last version of code on master is not stable?

**Comment by jpahullo** [comment]
could someone accept this PR please?

**Comment by jpahullo** [comment]
I can see that the other PR has passed all CI. However, this one not, neither the one from David Monllaó, coursiously in the same second job.

**Comment by jpahullo** [comment]
I don't know... there is no sense on this failure when this PR only applies this change:

single change on .gitignore

**Comment by jpahullo** [comment]
I can see from [stackoverflow](https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit) that users with write access can rerun the build. Can someone, please, rerun the build?

**Comment by stronk7** [comment]
(relaunched)

**Comment by jpahullo** [comment]
Thanks a lot @stronk7! You're very kind!

There were another error on the CI, now related to a test about localcache:

```
There was 1 failure:
1) core_setuplib_testcase::test_localcachedir
Time is lower that allowed start value
Failed asserting that 1580781629 is equal to 1580781630 or is greater than 1580781630.
/var/www/html/lib/phpunit/classes/advanced_testcase.php:449
/var/www/html/lib/tests/setuplib_test.php:117
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit --verbose "core_setuplib_testcase" lib/tests/setuplib_test.php
--
```

Nothing related to ignoring `.env` file within `.gitignore`.

Any ideas why this CI is randomly failing (see the other error from before)? This is somehow difficult to contribute to.

Thanks a lot!

**Comment by nadavkav** [comment]
Would love to see this PR integrated

**Comment by iwasherefirst2** [comment]
Is it possible that files of the commit have been deleted? I only see an empty `.env` file but no script changes to read any values out of it.

**Comment by jpahullo** [comment]
Hi @iwasherefirst2, Yes, this commit only ignores the .env from the repo, since docker-compose commands loads .env files automatically. I've seen your contribution at #130 and seems more complete than this one. Closing this PR. Thanks ofr your time.

**Pull request closed without merging**
