### PR TITLE
Update README.md due Xdebug 2 to 3 upgrade

### PR DESCRIPTION
**Pull request by adpe**
https://xdebug.org/docs/upgrade_guide

PR result of this message https://t.me/moodledev/90141

image

### CODE REVIEW

**Comment by stronk7** [comment]
Just cross-linking to #146 because in that issue there were some extra config settings that we may want to have documented, feel free to discuss about anything here.

Ciao :-)

**Comment by djhipps** [comment]
I have reviewed the above and confirm that 

> read -r -d '' conf <<'EOF'
> ; Settings for Xdebug Docker configuration
> xdebug.mode=debug
> xdebug.client_host=host.docker.internal
> xdebug.idekey=VSCODE
> EOF

is suffient for me and some of the settings in #146 were superflous.

**Comment by stronk7** [comment]
So, the `idekey` is needed, correct? Or am I wrong and it's not needed?

Maybe it's the IDE the one requiring it? For example, I remember myself playing with it with `vim` and I think it was not needed (in fact I don't have it defined in my `php.ini` files.

What about adding it commented out, sort of:
```
; Some IDEs (list, of, ides, known, to, require, it...) may require to configure an idekey, uncomment if needed
; xdebug.idekey=MY_FAV_IDE_KEY
````

Ciao :-)

**Comment by stronk7** [comment]
And merged, thanks!

**Pull request merged**
