### PR TITLE
Fixed CI build failure.

### PR DESCRIPTION
**Pull request by scara**
Fixed a failure in a GeoIP unit test, found while reviewing #79

### CODE REVIEW

**Comment by scara** [comment]
Pinning the _pgsql_ version looks like harder than moving to the latest Moodle version.

Refs:
- https://github.com/travis-ci/travis-ci/issues/9346
- [MDL-61626](https://tracker.moodle.org/browse/MDL-61626)

**Comment by scara** [comment]
Will update the PR by moving to `3.3.5` just released which runs smoothly with any known version of pgsql (MDL-61626).

**Comment by stronk7** [comment]
+1 to move to just released. In fact surely could move to 3.4.2. I'm happy either way, TIA!

**Comment by scara** [comment]
PR rebased.
@stronk7: we should stick w/ 3.3.x since here we're still testing against PHP 5.6 too.

HTH,
Matteo

**Comment by stronk7** [comment]
> we should stick w/ 3.3.x since here we're still testing against PHP 5.6 too.

Good point, you're right, thanks!

**Pull request merged**
