### PR TITLE
Add env variables to control the ip address a port binds to

### PR DESCRIPTION
**Pull request by abias**
This PR solves issue #64.
With this patch, I decided to bind to localhost-only from now on. This is a change in the current default behavior, but it will improve the security of the docker containers.

### CODE REVIEW

**Comment by danpoltawski** [comment]
I'm really in favour of trying to avoid too many variables introduced (see #60, heh) - do we really need two variables for this? Can't we just change the default value to use a localhost bound port?

**Comment by abias** [comment]
Thanks, Dan, for your instant feedback.

Before I started writing this patch, I thought about the use cases for using this docker environment. Sure, it was built for local testing first. The local development use case joined the party later. And we can be pretty sure that nobody will use this docker configuration in production. So, it would make sense to just change the port binding and that's it.

However, personally, I try to avoid any hardwired functionality which doesn't cover all use cases. I can also think of these usage scenarios:
* A tester sets up a Moodle docker instance on a powerful testing server in his subnet, but accesses it from his Desktop machine. In this case, he would have to control the IP address / network interface the webserver and the selenium ports bind to.
* A developer sets up a Moodle docker instance on his Desktop machine for local development and testing, but wants to give access to the webserver to colleagues in his subnet for discussing current developments. In this case, he would want to bind the webserver port to a public IP address, but not the Selenium port.

So I went for two variables and in my personal point of view, this is fine as long as there is a default setting which fits for the majority of users / use cases.

I you really don't like this solution, I will be happy to rebuild the patch to only one env variable or even just changing the default to localhost.

Thanks,
Alex

**Comment by danpoltawski** [comment]
Sorry I misspoke a little - I mean that we can use the 2 existing variables and not have 4 for it.

You can either choose `8000`, `0.0.0.0:8000`, `127.0.0.1:8000`, `10.0.0.2:8000` (etc). No need to split it into two variables to achieve this functionality.

**Comment by abias** [comment]
Ah, I see. Indeed you're right, we could reuse the existing variables and it would just be a matter of documentation then. The reason why I invented another variable was to keep both matters logically separated. But I agree that someone who is able to start a docker container should hopefully also be able to understand what `127.0.0.1:8000` means.

So I could rebuild my PR. How do you feel about changing the default binding from worldwide to localhost-only? Should I still do this or better keep the current binding?

**Comment by scara** [comment]
> How do you feel about changing the default binding from worldwide to localhost-only? Should I still do this or better keep the current binding?

Since I'm using a docker engine outside my dev machine, I'd say I'd prefer to stick w/ the current setting 😉 but I could be the only one w/ this setup so up to you @danpoltawski and @abias.

**Comment by abias** [comment]
Hi Dan,

May I ping you about the question of changing the default binding?

Additionally, I went back to the start and just added the IP address to the port environment variable. Here's what I got:

```
$ export MOODLE_DOCKER_WEB_PORT=127.0.0.1:8000
$ bin/moodle-docker-compose up -d
bin/moodle-docker-compose: line 72: [[: 127.0.0.1:8000: syntax error: invalid arithmetic operator (error token is ".0.0.1:8000")
Creating network "moodlemaster_default" with the default driver
Creating moodlemaster_db_1 ... 
Creating moodlemaster_mailhog_1 ... 
Creating moodlemaster_selenium_1 ... 
Creating moodlemaster_db_1
Creating moodlemaster_mailhog_1
Creating moodlemaster_mailhog_1 ... done
Creating moodlemaster_webserver_1 ... 
Creating moodlemaster_webserver_1 ... done
```

So, if we would combine IP and Port into the existing variable, I would have to replace the arithmetic check at line 72 with a weaker check or split the port from the IP with some effort. Do you think this is better than having two separate environment variables?

**Comment by danpoltawski** [comment]
My view:

- Yes, one variable
- Yes, default to localhost only

**Comment by scara** [comment]
Worth reading #67 to validate the _scope_ covered by this pull.

**Comment by nicoroeser** [comment]
A single variable is not possible since 5110384218a92e64966cb032fc6526f294dfce90 (fix for #24). Reason is that `config.docker-template.php` uses the port from the environment variable, and that must not also contain a hostname/IP (or it would have to be parsed).

Considering this, I suggest to merge the pull request as-is. The patch applies cleanly on current `master`. It has the nice additional property that you can also run several instances on the same (outside-facing) port, but different (outside-facing) host.

**Comment by stronk7** [comment]
Hi,

sorry for the late reply... I've been re-reading this over the last days and considering it under all views.. and my opinion pretty much coincides with @danpoltawski one above, aka:

* Yes, one variable.
* Yes, localhost only bind by default.

I've spent some minutes preparing this quick (and dirty) patch that provides that for MOODLE_DOCKER_WEB_PORT: https://github.com/stronk7/moodle-docker/commit/a489524725b33ed23f5a5ba157d421f5b7b3bb3e

Basically, port defaults to 8000 if not specified and, then, bind_port defaults to 127.0.0.1 if not specified. Have tried it here with:

- nothing => 127.0.0.1:8000
- 999 => 127.0.0.1:999
- 0.0.0.0:999 => 0.0.0.0:999

and seems to be working ok. Please take a look to the patch and comment.

TODO:

- So a similar implementation for the VNC thingy.
- Try the CMD alternative. My Windows docker is only able to run Windows containers (and I've been unable to activate the linux ones, have tried near everything) so I cannot test it properly.

Comments welcome, ciao :-)

**Comment by abias** [comment]
Hi @stronk7 ,

thank you for picking this up.

I had a look at your alternative patch and can report this:
* It worked with my setup on Docker for Mac
* It does not look as dirty as you classified it ;)
* I don't have any reason to argue again if a single-variable or a multi-variable solution is cleaner and would go with your proposal as it works.
* Defaulting to localhost makes sense
* From my point of view, the implemented logic can be directly applied to the VNC thingy. It's just copy & paste.
* I, unfortunately, also can't test the Windows CMD and would appreciate if others could test this.

If I can do anything to bring this to a state which is ready to be merged, please let me know.

Cheers,
Alex

**Comment by stronk7** [comment]
About windows... after fighting here over months because for some mysterious reason linux containers in my windows laptop were not working (bios, reports, debugging, mails...no luck) and I had abandoned it... just yesterday... withe the last update... it magically started working... so I'm proud to say that now I can test it too.

If fact, it's failing now, heh (beloved batch doesn't support AND/OR conditions, fun!). So I'll try to:

- guarantee it's working under windows.

then, if you can "steal" it from me and apply it to VNC... I'd be happy to review and merge the final implementation (that really will help here because we these are specially struggling days).

**Comment by abias** [comment]
> then, if you can "steal" it from me and apply it to VNC... I'd be happy to review and merge the final implementation (that really will help here because we these are specially struggling days)

OK, that sounds like a deal.
You fix the CMD version as soon as you have time and I will then update the pull request with your proposal including a solution for VNC

**Comment by stronk7** [comment]
Ok, I think I've got the batch working as expected (like the unix shell does):

````
C:\Users\stronk7\git_moodle\moodle-docker>set MOODLE_DOCKER_WEB_PORT=0
C:\Users\stronk7\git_moodle\moodle-docker>bin\moodle-docker-compose.cmd up -d
WEBPORT: 0

C:\Users\stronk7\git_moodle\moodle-docker>set MOODLE_DOCKER_WEB_PORT=
C:\Users\stronk7\git_moodle\moodle-docker>bin\moodle-docker-compose.cmd up -d
WEBPORT: 127.0.0.1:8000

C:\Users\stronk7\git_moodle\moodle-docker>set MOODLE_DOCKER_WEB_PORT=999
C:\Users\stronk7\git_moodle\moodle-docker>bin\moodle-docker-compose.cmd up -d
WEBPORT: 127.0.0.1:999

C:\Users\stronk7\git_moodle\moodle-docker>set MOODLE_DOCKER_WEB_PORT=0.0.0.0:999
C:\Users\stronk7\git_moodle\moodle-docker>bin\moodle-docker-compose.cmd up -d
WEBPORT: 0.0.0.0:999
````

And here it is the current commit achieving that: https://github.com/moodlehq/moodle-docker/compare/master...stronk7:localhost_only_allinone

Ciao :-)

**Comment by tmuras** [comment]
Tested on Linux with https://github.com/moodlehq/moodle-docker/compare/master...stronk7:localhost_only_allinone patch:

1. No MOODLE_DOCKER_WEB_PORT
127.0.0.1:8000->80/tcp

2. MOODLE_DOCKER_WEB_PORT=8001
127.0.0.1:8001->80/tcp

3. MOODLE_DOCKER_WEB_PORT=127.0.0.1:8001
➜ bin/moodle-docker-compose up -d             
bin/moodle-docker-compose: line 76: [[: 127.0.0.1:8001: syntax error: invalid arithmetic operator (error token is ".0.0.1:8001")
Creating network "moodle-docker_default" with the default driver

**Comment by abias** [comment]
Hi @stronk7 ,

somehow this got thrown back on my side again unfortunately.

I have now successfully applied your patch to the lastest master, have added the necessary logic for the VNC port as well and have successfully tested the result on Mac OS:

## Setting web port

1. No `MOODLE_DOCKER_WEB_PORT` set
=> moodle-php-apache PORTS: `127.0.0.1:8000->80/tcp`

2. `MOODLE_DOCKER_WEB_PORT=8001`
=> moodle-php-apache PORTS: `127.0.0.1:8001->80/tcp`

3. `MOODLE_DOCKER_WEB_PORT=127.0.0.1:8001`
=> moodle-php-apache PORTS: `127.0.0.1:8001->80/tcp`
This means I can't reproduce the problem reported by @tmuras 

4. `MOODLE_DOCKER_WEB_PORT=192.168.178.5:8001`
=> moodle-php-apache PORTS: `192.168.178.5:8001->80/tcp`

5. `MOODLE_DOCKER_WEB_PORT=0.0.0.0:8001`
=> moodle-php-apache PORTS: `0.0.0.0:8001->80/tcp`

6. `MOODLE_DOCKER_WEB_PORT=0`
=> moodle-php-apache PORTS: No portforwarding to outside container


## Setting VNC port

1. No `MOODLE_DOCKER_SELENIUM_VNC_PORT` set
=> Only standalone-firefox image built
=> standalone-firefox PORTS: No portforwarding to outside container

2. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5900`
=> standalone-firefox-debug PORTS: `127.0.0.1:5900->80/tcp`

3. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5904`
=> standalone-firefox-debug PORTS: `127.0.0.1:5904->80/tcp`

4. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5900`
=> standalone-firefox-debug PORTS: `127.0.0.1:5900->80/tcp`

5. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5904`
=> standalone-firefox-debug PORTS: `127.0.0.1:5904->80/tcp`

6. `MOODLE_DOCKER_SELENIUM_VNC_PORT=192.168.178.5:5900`
=> standalone-firefox-debug PORTS: `192.168.178.5:5900->80/tcp`

7. `MOODLE_DOCKER_SELENIUM_VNC_PORT=192.168.178.5:5904`
=> standalone-firefox-debug PORTS: `192.168.178.5:5904->80/tcp`

8. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5900`
=> standalone-firefox-debug PORTS: `0.0.0.0:5900->80/tcp`

9. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5904`
=> standalone-firefox-debug PORTS: `0.0.0.0:5904->80/tcp`

10. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0`
=> Only standalone-firefox image built
=> standalone-firefox PORTS: No portforwarding to outside container

----

Regarding the Windows script, I was not able to test the VNC part due to the lack of a proper testing environment. I would be grateful if you could test this on your side again.

I hope this is then ready to be merged. If there is anything else which I should do, please let me know.

Cheers,
Alex

**Comment by stronk7** [comment]
Thanks @abias , as a funny thing I arrived here because I was watching some travis runs related to the code-checker and suddenly a new run about moodle-docker appeared magically (your PR push).

Ok, so all I need is to verify that all those VNC combinations are working ok under windows, correct?

Will review it all too, just in case. Thanks!

**Comment by stronk7** [comment]
Ok, first I've tried it on **LINUX**, just to discard there is any difference with macos and ensure that @tmuras case is fixed / cannot reproduce:

## Setting web port

1. No `MOODLE_DOCKER_WEB_PORT` set
=> 127.0.0.1:8000->80/tcp

2. `MOODLE_DOCKER_WEB_PORT=8001`
=> 127.0.0.1:8001->80/tcp

3. `MOODLE_DOCKER_WEB_PORT=127.0.0.1:8001`
=> 127.0.0.1:8001->80/tcp
(hence, cannot reproduce the problem either) 

4. `MOODLE_DOCKER_WEB_PORT=172.25.0.1:8001`
=> 172.25.0.1:8001->80/tcp

5. `MOODLE_DOCKER_WEB_PORT=0.0.0.0:8001`
=> 0.0.0.0:8001->80/tcp

6. `MOODLE_DOCKER_WEB_PORT=0`
=> 80/tcp (no forwarding outside dockerland)

## Setting VNC port

1. No `MOODLE_DOCKER_SELENIUM_VNC_PORT` set
=> 4444/tcp (no forwarding outside dockerland)

2. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5900`
=> 4444/tcp, 127.0.0.1:5900->5900/tcp

3. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5904`
=> 4444/tcp, 127.0.0.1:5904->5900/tcp

4. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5900`
=> 4444/tcp, 127.0.0.1:5900->5900/tcp

5. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5904`
=>  4444/tcp, 127.0.0.1:5904->5900/tcp

6. `MOODLE_DOCKER_SELENIUM_VNC_PORT=172.25.0.1:5900`
=> 4444/tcp, 172.25.0.1:5900->5900/tcp

7. `MOODLE_DOCKER_SELENIUM_VNC_PORT=192.168.178.5:5904`
=> 4444/tcp, 172.25.0.1:5904->5900/tcp

8. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5900`
=> 4444/tcp, 0.0.0.0:5900->5900/tcp

9. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5904`
=> 4444/tcp, 0.0.0.0:5904->5900/tcp

10. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0`
=> 4444/tcp (no forwarding outside dockerland)

----

So it seems that everything is working ok against (Ubuntu 16.04) linux. Only curiosity I've found when running your combinations, @abias ... is that in your combinations for Mac you have `...590x->80/tcp` ... is that correct? How did you end with VNC running @ port 80? It always run @ port 5900 internally.

In the mean time... I'm going ro run exactly the same unde windows now. Ciao :-)

**Comment by abias** [comment]
Hi @stronk7 ,

> Ok, so all I need is to verify that all those VNC combinations are working ok under windows, correct?

Exactly.

> Only curiosity I've found when running your combinations, @abias ... is that in your combinations for Mac you have ...590x->80/tcp ... is that correct? How did you end with VNC running @ port 80? It always run @ port 5900 internally.

Oh, that's my fault. I did a copy & paste of the test steps of the web port list to the vnc port list and must have forgotten to change the internal VNC port from 80 to 5900. Of course, you are right and it also runs on 5900 on my side. Sorry for this disturbance.

Cheers,
Alex

**Comment by stronk7** [comment]
Sorry for the delay with the Windows runs... I'm facing some problems here when trying to bind Windows to one of my network interfaces (it works perfectly with both 127.0.0.1 and 0.0.0.0), so I've spent quite a lot of time reinstalling hyper-V and docker, trying different solutions I've seen in the web, no one successful... in fact there are lots of places saying that it doesn't work and need to add routes and other things to enable that... and I'm not going to spend more time on that use case, I'm afraid.

So, I'm going to skip that case (bind to just one of the interfaces in windows), in order to check all the rest... and f they go ok... PUSH and forget! :-)

Just an update, grrr. windows...

**Comment by stronk7** [comment]
And these are the **WINDOWS** runs:

## Setting web port

1. No `MOODLE_DOCKER_WEB_PORT` set
=> 127.0.0.1:8000->80/tcp

2. `MOODLE_DOCKER_WEB_PORT=8001`
=> 127.0.0.1:8001->80/tcp

3. `MOODLE_DOCKER_WEB_PORT=127.0.0.1:8001`
=> 127.0.0.1:8001->80/tcp

4. `MOODLE_DOCKER_WEB_PORT=x.y.w.z:8001`
=> **Binding to single not working here (and have tried lots of things). Skipping the case!**

5. `MOODLE_DOCKER_WEB_PORT=0.0.0.0:8001`
=> 0.0.0.0:8001->80/tcp

6. `MOODLE_DOCKER_WEB_PORT=0`
=> 80/tcp (no forwarding outside dockerland)

## Setting VNC port

1. No `MOODLE_DOCKER_SELENIUM_VNC_PORT` set
=> 4444/tcp (no forwarding outside dockerland)

2. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5900`
=> 4444/tcp, 127.0.0.1:5900->5900/tcp

3. `MOODLE_DOCKER_SELENIUM_VNC_PORT=5904`
=> 4444/tcp, 127.0.0.1:5904->5900/tcp

4. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5900`
=> 4444/tcp, 127.0.0.1:5900->5900/tcp

5. `MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:5904`
=>  4444/tcp, 127.0.0.1:5904->5900/tcp

6. `MOODLE_DOCKER_SELENIUM_VNC_PORT=x.y.w.z:5900`
=> **Binding to single not working here (and have tried lots of things). Skipping the case!**

7. `MOODLE_DOCKER_SELENIUM_VNC_PORT=x.y.w.z:5904`
=> **Binding to single not working here (and have tried lots of things). Skipping the case!**

8. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5900`
=> 4444/tcp, 0.0.0.0:5900->5900/tcp

9. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:5904`
=> 4444/tcp, 0.0.0.0:5904->5900/tcp

10. `MOODLE_DOCKER_SELENIUM_VNC_PORT=0`
=> **4444/tcp, 127.0.0.1:<random>->5900/tcp** Incorrect, no debug should be used here.

----

So, summary for windows:

A) All the cases trying to bind to just one interface are failing. I don't know if this is docker problem/limitation or local lack of configuration to allow that. As far as both loopback and all interfaces are working... I think this is ok. Surely somebody with more Windows abilities would be able to fix this (routes, virtual switches or whatever, I'm not).

B) Case 10 (vnc_port=0) is not working as expected. It seems that the selenium-debug is being used there and it should not. I think the fix is as simple as moving the 2 lines related to use the -debug option to within the inner condition:

````
--- a/bin/moodle-docker-compose.cmd
+++ b/bin/moodle-docker-compose.cmd
@@ -66,17 +66,17 @@ IF DEFINED TRUE (
 IF "%MOODLE_DOCKER_SELENIUM_VNC_PORT%"=="" (
     SET MOODLE_DOCKER_SELENIUM_SUFFIX=
 ) ELSE (
-    SET MOODLE_DOCKER_SELENIUM_SUFFIX=-debug
     SET "TRUE="
     IF NOT "%MOODLE_DOCKER_SELENIUM_VNC_PORT%"=="%MOODLE_DOCKER_SELENIUM_VNC_PORT::=%" SET TRUE=1
     IF NOT "%MOODLE_DOCKER_SELENIUM_VNC_PORT%"=="0" SET TRUE=1
     IF DEFINED TRUE (
+        SET MOODLE_DOCKER_SELENIUM_SUFFIX=-debug
+        SET DOCKERCOMPOSE=%DOCKERCOMPOSE% -f "%BASEDIR%\selenium.debug.yml"
         REM If no bind ip has been configured (bind_ip:port), default to 127.0.0.1
         IF "%MOODLE_DOCKER_SELENIUM_VNC_PORT%"=="%MOODLE_DOCKER_SELENIUM_VNC_PORT::=%" (
             SET MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:%MOODLE_DOCKER_SELENIUM_VNC_PORT%
         )
     )
-    SET DOCKERCOMPOSE=%DOCKERCOMPOSE% -f "%BASEDIR%\selenium.debug.yml"
 )
````

With that... the selenium-debug only will be used when there is something defined not being 0. Everything else should continue working ok.

Would you, @abias, amend your last commit? I've run the 10 tests here with that applied and everything worked ok, so far (but the case A above that we shouldn't mind anymore).

Ciao :-)

**Comment by abias** [comment]
Thanks, @stronk7 , for having another look.

> A) All the cases trying to bind to just one interface are failing.

I am not a Windows guy and can't help with this either. But I agree that it's no use to spend more time into that case as long as localhost-only and all interfaces are working.

> B) Case 10 (vnc_port=0) is not working as expected. 

You are fully right. Like the Windows code was written, the debug image is used as soon as $MOODLE_DOCKER_SELENIUM_VNC_PORT is not empty. The Linux code was written slightly differently and does a check if $MOODLE_DOCKER_SELENIUM_VNC_PORT is greater than zero.

I think this case 10 is more academic than realistic. I just added it for the sake of completeness, but surely it should work as expected.

Thus, I am happy to change the script according to your proposal and push an updated branch to this PR.

Cheers,
Alex

**Comment by stronk7** [comment]
Sold, yay! Thanks @abias et all!

**Pull request merged**
