### PR TITLE
removed old config vars removed in newer MariaDB

### PR DESCRIPTION
**Pull request by deer667**
Based on https://mariadb.com/kb/en/innodb-system-variables/

### CODE REVIEW

**Comment by deer667** [comment]
Might be also worth to expand tests for 7.3 and 7.4 PHP version with MariaDB as the ones that were run cover only up to 7.2.

**Comment by scara** [comment]
Hi @deer667,
> Might be also worth to expand tests for 7.3 and 7.4 PHP version with MariaDB as the ones that were run cover only up to 7.2.
what do you mean?

you can already select the PHP version to run your tests w/ by means of properly setting the `MOODLE_DOCKER_PHP_VERSION` ENV VAR.

HTH,
Matteo

**Comment by deer667** [comment]
Hello @scara,

> Hi @deer667,
> 
> > Might be also worth to expand tests for 7.3 and 7.4 PHP version with MariaDB as the ones that were run cover only up to 7.2.
> > what do you mean?
> 
> you can already select the PHP version to run your tests w/ by means of properly setting the `MOODLE_DOCKER_PHP_VERSION` ENV VAR.
> 
> HTH,
> Matteo

I was thinking about automated tests that are running after pull request, so basically travis.yml. Currently I am running production Moodle 3.9.1 on MariaDB 10.4.14 and PHP 7.4.9 without issues (except deprecated vars in innodb settings :) ). Not sure if it is needed though.

Chris

**Comment by scara** [comment]
Hi @deer667,
OK, Travis CI is managed in the https://github.com/moodle/moodle repo via https://tracker.moodle.org/projects/MDL/issues/.

Time ago there was a policy to limit the "pressure" against Travis CI runs, testing Moodle code just on the highest and lowest among the PHP supported versions: tests on `pgsql` are running faster i.e. MySQL-ish runs just on PHP upper supported version using MySQL and not MariaDB.
It could be proposed there in the Tracker, given that the time required to complete Travis jobs will be increased - depending when jobs runs on a pure parallel queueing - by about 30 minutes per each new `PHPUNIT` run: @timhunt already proposed it hijacking a bit the scope of [MDL-66263](https://tracker.moodle.org/browse/MDL-66263).

HTH,
Matteo

**Comment by stronk7** [comment]
Hi,

I've picked your commit and then added an [highly modified .travis.yml](https://github.com/stronk7/moodle-docker/blob/e22216f568604a1074fe76012ee8b7d7e3a7decd/.travis.yml) to, extensively, verify that this works for all PHP and Moodle combinations. I think it will, but better confirm.

Link: https://travis-ci.org/github/stronk7/moodle-docker/builds/726356431

Let's see how it ends (will take a while). Thanks @deer667 (and @scara ) !

PS: And, yes, we cannot test all combos always, neither here, neither in moodle. Although we have a good % of combinations continuously covered, if we add our lovely: https://ci.moodle.org to the equation.

**Comment by stronk7** [comment]
As far as the travis run above is failing all combinations, because of the 50 minutes time limit per job (although it's running without failures till the timeout happens), I've also launched some jobs @ ci.moodle.org, with exactly the very same 2 variables removed (both for MariaDB - unpinned and MySQL 5.7):

master branch:
- MariaDB / PHP7.4: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1666/)
- MariaDB / PHP7.3: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1668/)
- MariaDB / PHP7.2: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1667/)
- MySQL / PHP7.4: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1662/)
- MySQL / PHP7.3: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1669/)
- MySQL / PHP7.2: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1663/)

35_STABLE branch:
- MariaDB / PHP7.2: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1672/)
- MariaDB / PHP7.1: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1671/)
- MariaDB / PHP7.0: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1670/)
- MySQL / PHP7.2: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1673/)
- MySQL / PHP7.1: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1674/)
- MySQL / PHP7.0: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1675/)

The runs above shouldn't be subject to any time restriction, let's see.

**Comment by stronk7** [comment]
The runs look ok.

1) there is a random failure that we have registered, so unrelated with the MariaDB/MySQL changes.
2) there are the problems with solr and the php71 image that I will investigate apart.

So I think it's ok to proceed with the change, I will proceed in few hours if nobody is against it.

**Comment by stronk7** [comment]
With https://github.com/moodlehq/moodle-php-apache/pull/116 merged, rerunning the php71 jobs:

- MariaDB: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1678/)
- MySQL: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/1679/)

**Comment by stronk7** [comment]
Merged, thanks!

**Pull request merged**
