### PR TITLE
Adding phpMyAdmin support for MySQL and MariaDB databases.

### PR DESCRIPTION
**Pull request by rlorenzo**
I found it useful to have phpMyAdmin during Moodle development. Hopefully others will as well.

### CODE REVIEW

**Comment by scara** [comment]
Just sharing a thought: should any additional web-based _service_ be proxied to avoid using new TCP ports? See https://github.com/moodlehq/moodle-docker/blob/master/assets/web/apache2_mailhog.conf and https://github.com/moodlehq/moodle-docker/pull/24#issuecomment-318362082.

HTH,
Matteo

**Comment by danpoltawski** [comment]
> should any additional web-based service be proxied to avoid using new TCP ports?

Yes, I think this is a good idea. (i’m not completely sold on us adding phpmyadmin by default)

**Comment by scara** [comment]
> I’m not completely sold on us adding phpmyadmin by default

I'm but I'd vote for https://www.adminer.org/ in this case, being cross-DBs (MySQL, PostgreSQL, SQLite, MS SQL, Oracle, SimpleDB, Elasticsearch, MongoDB).

It could be useful when your dev env is not hosted in the same machine where the docker daemon is running (mine :wink:, #33); e.g. when working w/ https://tracker.moodle.org/browse/MDL-59100 (and related) I've used the CLI client, from the `db` container, to connect to the DB and a Web-based solution would have speed up some investigation works.

HTH,
Matteo

**Comment by danpoltawski** [comment]
Hi Rex,

We talked about this a bit in HQ and I'm going to close this pull request because I didn't really think it was the right choice and i couldn't get others to support the idea either.

There are a few things against it:

- It is just one method of accessing database which is not universally applicable (many will use other tools like GUI applications, or if you are like me, the CLI tools only)
- This only supports the one db engine rather than something like adminer which could apply to all the different db engines
- It seems like installing local_adminer in your codebase would not require this adding to the docker images

Overall, it's a sort of 'opinionated close' that I don't think it's worth adding this to the images - but I think it's better that we close this than keep it open in limbo.

**Pull request closed without merging**
